name = "Relax Pack"
author = "Munsterlandr"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1568677dab473c1845accce4dc8ee992fbff6f4aea27832af2f47c42d1b36882"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
