name = "Relax Pack"
author = "Munsterlandr"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b93aabaa75b70a9c119e195809b2926470dab1c61bbf21bbc849c43c08ee08c0"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
